src/niivue.js
src/nvimage.js
src/shader-srcs.js

- getValue returns luminance for RGB/RGBA images, [closes issue 42](https://github.com/niivue/niivue/issues/42).
- Support for int64 (overflows if value exceeds 2^53). Handles masks and segmentation maps created by [nibabel](https://github.com/nipy/nibabel/issues/1046) and [nilearn](https://github.com/nilearn/nilearn/issues/3167) users.

RGB fixes and INT64 support

---

src/niivue.js
src/shader-srcs.js

Tested on MacOS (M1) and Windows (Nvidia GPU). 
- The depth picker uses `readPixels` to determine depth. On some platforms (e.g. Windows) the default is to blend the color value with the background. So if the shader writes [0.9, 0.9, 0.9, float(2)/255.0] read pixels will return RGB components that are all near zero. In contrast, on macOS one gets bright RGB values.  Perhaps we should explicitly disable the alpha test prior to reading pixels:
```
glDisable(GL_ALPHA_TEST);
glReadPixels(0, 0, bmpg32.Width, bmpg32.Height, GL_BGRA , GL_UNSIGNED_BYTE, Bdata);
```
My simple hack was to simply change `this.VOLUME_ID = 2` to `this.VOLUME_ID = 250` (e.g. a value near 255).
- The picking shader did not have the `overlays` uniform set. This is now set and the picking shader will select the location …

Fix depth picking

---

src/niivue.js

Fixes a simple bug seen in 2D views of all the demos. If a use right-clicked without dragging (regardless if on our outside image), calculateNewRange() would generate bogus values.

Ensure calculateNewRange() has intensity variability

---

package.json

Including niivue in OpenNeuro (which uses Vite and SSR so needs CJS and ESM entrypoints) encounters this warning:
```
@niivue/niivue doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
```
This should fix this by adding export mappings [borrowed from the building for libraries example in Vite's docs](https://vitejs.dev/guide/build.html#library-mode).

Packaging fix for `niivue doesn't appear to be written in CJS` when imported into Vite / SSR projects

---

src/shader-srcs.js

This PR fixes the artifact reported in #344. 
However, I don't know enough about the niivue internals to understand the ramifications of removing these clauses.  Specifically, I don't know where the `<voxel intensity>->RGBA` transfer function is defined, nor what the resulting alpha values represent.  These clauses were present in the very first commit on the niivue/niivue github repository, so there is no provenance as to what they intend to accomplish. @neurolabusc, do you have any insight here?
- #344 
Demos work on:

BF: Avoid use of continue statement in raycast loop, to work around apparent mesa bug

---

demos/features/sync.mesh.html
demos/index.html
src/niivue.js

List of fixed issues:
- 3D crosshairs influenced by `crosshairWidth`
- 2D world space views show crosshairs regardless of `show3Dcrosshair`
- multiplanarPadPixels generates console message if non-numeric value is supplied and uses parseFloat() to convert strings to numbers. In general, user interfaces should supply numeric values to parameters, not strings. In other words, the text string "3" is not the same as the number 3.

Little fixes

---

src/niivue.css
src/niivue.js

- The last PR flips negative colorbars so the left side is brighter (like AFNI, FSLeyes and BrainVoyager, but unlike MRIcroGL. Depending on screen size, this could lead to the [alphathreshold demo](https://niivue.github.io/niivue/features/alphathreshold.html) not showing the colorbar. This PR disables CULL_FACE to fix this problem.

Disable cull face for mirror-flipped statistics

---

src/nvmesh.js

Linked to https://github.com/nilearn/nilearn/issues/3451#issuecomment-1416174323.
Closes #496.
This PR creates a new method `NVMesh.loadLayer()` which populates a layer buffer with information communicated through the `base64` parameter if it exists or through the `url` parameter otherwise.
Both `NVMesh.loadFromBase64()`, `NVMesh.loadFromUrl()` and `NVMesh.loadFromFile()` all call this function for each layer.

Load mesh from base64 or from url

---

src/nvmesh.js

- More robust parsing of white space in ASCII mesh formats. Previously, NiiVue assumed a single space as the white space delimiter for ASCII text mesh formats. However, some formats are interpreted liberally, for example with multiple spaces between items. An example is [this teapot in obj format](https://people.sc.fsu.edu/~jburkardt/data/obj/obj.html).

Mesh import improvement

---

package-lock.json
package.json

- bump nifti reader js version to reflect latest changes (0.6.4)

Bump nifti reader js version

---

demos/features/draw2.html
src/niivue.js

- closes #628 
- Allow drawBitmap to act as mask for descriptives
- add volume metrics to returned info from getDescriptives

add volume metrics; allow drawing to be mask

---

demos/features/tracts.group.html

- This fixes a bug with the [new fiber group live demo](https://niivue.github.io/niivue/features/tracts.group.html). After setting a group coloring, you need to unset the group coloring to apply a whole-tract color mechanism.

Close fiberGroupColormap when setting a non-group color scheme

---

.gitignore
package.json
src/niivue.js
tests/test.embedUMD.js
vite.config.js
vite.config_inject.js

- related to #682 and #680 
- added a new vite config file to embed the previously bundled niivue UMD (now a two stage build process)
- the new build process does this:
1.   first pass builds niivue.es.js and niivue.umd.js
2. second pass reads the contents of niivue.umd.js via the new vite config file and injects the base64 encoded, compressed version of niivue.umd.js
3. The build is actually not as large as estimated, so the size cost of doing this is negligible 
- added a new function to niivue: `decodeEmbeddedUMD()`. This function will decode the base64 string and decompress the embedded Niivue UMD bundle so that the string contents can be injected into HTML files that Niivue saves.
- To try it, you can put `console.log(this.decodeEmbeddedUMD());` …

add two stage build to inject niivue UMD

---

src/nvimage.js

List of fixed issues:
- The DICOM slice thickness was used as pixel depth, but the pixel depth should be calculated using the offsets between subsequent slices. The slice thickness is frequently larger than the slice spacing, and in case of tilted slices (used in helical CT's, for example), the pixel depth is larger than the slice spacing because of the skew.

Fix DICOM scaling

---

src/index.html
src/niivue/index.ts
src/nvmesh-loaders.ts
src/nvmesh-types.ts
src/nvmesh.ts

- https://github.com/niivue/niivue/issues/839
- https://github.com/niivue/niivue/issues/830
- https://github.com/niivue/niivue/issues/829
@cdrake or @jens-ox I do not know how to resolve the typescript issues. The Matlab files are similar to a JSON file where there can be an arbitrary number of named fields, each with an array of numbers that can be of various datatypes (int8, uint32, float64, etc).

Small fixes

---

src/index.html
src/nvmesh-loaders.ts
src/nvmesh.ts

- This [doubles the speed](https://github.com/neurolabusc/trx-javascript/tree/main) for loading TRK and TCK format tractography data
- @jens-ox the new javascript code runs, but the TypeScript generates errors as the functions return vertices are of type `Float32Array` rather than `number[]` and offsets of of type `Uint32Array` rather than `number[]`. My own sense is that **all** tractography data types (TRACT, TT, TRX, TRK, TCK, and VTK) should return these typed arrays. Do you have a strong opinion on this?

Accelerate TRK and TCK loading

---

src/niivue/index.ts
src/nvimage/index.ts
src/nvutilities.ts
tests/unit/nvimage.test.ts
tests/unit/nvutilities.test.ts

Moved function implementations with no member data access to NVUtilities(sph2cartDeg and vox2mm) and NVImage specific functions to NVImage (vox2frac, frac2vox, mm2frac, and frac2mm) to NVImage. Left function stubs in niivue. 
Converted the following jest tests to vitest unit tests:
- test.sphere2cart.js
- test.vox2frac.js
- test.vox2mm.js
- test.zerosLike.js

Refactor niivue functions to child objects

---

playwright/e2e/helpers.js
playwright/e2e/test.niivue.flexboxResize.spec.ts
src/niivue/index.ts
tests/flexbox.html
tests/helpers.js

Fixes #862, but not perfectly.
When viewport height is gradually increased, the canvas' height increases at 4x the rate of change
https://github.com/niivue/niivue/assets/20404439/a77cc287-bb78-4ece-af51-e2234bf5a211
When viewport height is gradually decreased, the canvas' height increases at 3x the rate of change
https://github.com/niivue/niivue/assets/20404439/14498b5d-f8c6-47c4-956a-1e586f1802a3
- When viewport height is gradually increased, the canvas' height increases at 0.99x the rate of change (visually correct behavior)
- When viewport height is gradually decreased, the canvas' height is at first unchanged, then decreases (incorrect behavior, however it is nonetheless a preferable outcome)
https://github.com/niivue/niivue/assets/20404439/66f6b6a0-d5ab-4fe2-bcbc-edb12836fe0b
- …

Canvas sizing in flexbox parent

---

playwright/e2e/test.niivue.setCrosshairWidth.spec.js
src/niivue/index.ts

Fixed a bug and added a regression test. Previously, an error would be raised:
```
TypeError: Cannot read properties of null (reading 'mm')
```

Fix setCrosshairWidth when this.crosshairs3D is null

---

src/index.html
src/niivue/index.ts

- closes #861 
@jennydaman , please checkout the `bug-isresizecanvas` branch and then run `npm run dev`. The example web page that loads should automatically resize the parent element of the canvas, and trigger a proper redrawing of the canvas. 
So, now niivue will be aware of window resize events AND the resize events of the `canvas` parent element. This implementation uses the `ResizeObserver` which should be available in all major browsers. 
@jennydaman , you should be able to remove your [workaround](https://github.com/jennydaman/ChRIS_ui/commit/8b1e3ac96629967712e6370e074d897f0b8f32b0) once this is published in a new version of Niivue.

Fix canvas parent resizing issue

---

.github/workflows/ghpages.yml

This PR fixes the broken live demos due to a build script change.

run correct build command for online demos

---

demos/features/modulate.html
demos/features/modulateAfni.html
demos/features/modulateScalar.html
src/niivue/index.ts

Previously, the `idModulation` argument to `setModulationImage` could accept a string or `null`. I have updated `setModulationImage` to only accept a string (or empty string) rather than both strings and `null`. The demos that use this feature have also been updated. To clear the modulation, a user must supply an empty string as the value for `idModulation`. 
I have checked that the AFNI usage of this feature is not impacted. 
- closes #859

only allow idModulation to be a string

---

src/index.html
src/nvconnectome.ts
src/nvdocument.ts
src/nvmesh-loaders.ts
src/nvmesh-types.ts
src/nvmesh.ts

@jens-ox this PR uses typed arrays for WebGL meshes, as you note in your [PR 937](https://github.com/niivue/niivue/pull/937). The number[] arrays are still used for some transient usage (where the larger memory footprint has less impact than long term storage). However, all mesh indices are unified as Uint32 and all mesh vertex positions are unified as Float32. I think this addresses the `help needed` request from your PR.

Optimize mesh types

---

src/nvimage/index.ts
tests/unit/nvimage.test.ts

This PR ensures that a new ID is given to cloned images in order to avoid ID based conflicts. 
A new unit test has been added for NVImage as well that will make sure this issue doesn't happen in the future. 
- closes #945

Fix clone method to generate a new ID

---

src/niivue/index.ts

add `generateMouseUpCallback` behaviour to `touchEndListener`. This enables the same behaviour that we see in `mouseUpListener` by reusing our existing functions. 
Also updated the handling of different `DRAG_MODE` values in the `touchEndListener` event.

better logic for dragMode in touchEnd

---

demos/features/document.atlas.html
demos/features/document.customdata.html
demos/index.html
playwright/e2e/test.niivue.saveDocument.spec.ts
src/niivue/index.ts
src/nvdocument.ts
src/nvimage/index.ts

Correctly saves and loads scenes with atlas and other .nii files with voxel offset not equal to 352
Converts color map label lookup table array into Uint8ClampedArray
- [Atlas not saving correctly](https://github.com/niivue/niivue/issues/976) 
- [Color not rendered from volumes with color map label](https://github.com/niivue/niivue/issues/977)
- [Add the capability to save custom data to NVDocument](https://github.com/niivue/niivue/issues/979)

Fix atlas saving/loading and color rendering for colormaplabel

---

typedoc.json

This PR fixes the error preventing github actions from building and publishing the niivue docs and live demos
- Typedoc removed the `media` config option and now automatically detects media links (https://github.com/TypeStrong/typedoc/blob/e7d88cef87e15310972f1c407a5603a30acbb78d/CHANGELOG.md?plain=1#L107)

remove unused "media" property from typedoc.json

---

demos/features/sync.bidirectional.html
src/niivue/index.ts
src/nvdocument.ts

This PR adds the `gamma` value to the `scene` in `NVDocument`. This enables syncing of the `gamma` property when using the `broadcastTo` function of a `niivue` instance. 
see `demos/features/sync.bidirectional.html` for a reference of how this works in practice. 
- closes #1052

add support for gamma syncing

---

src/index.html
src/niivue/index.ts

This PR adds a cursor circle when `clickToSegment` is `true` and the user is hovering over a 2D tile. Cursor size is determined by `clickToSegmentRadius` which is specified in millimeters. 
- closes #1023

implement click to segment cursor

---

src/index.html
src/niivue/index.ts
src/nvdocument.ts

This PR adds the following options for the measurement tool
- `measureTextJustify: 'start'` (similar to css flexbox -- e.g. start, center, end)
- `showMeasureUnits: true` (20.2 vs 20.2 mm)
- `measureTextColor: [0, 1, 0, 1]` (the color of the text)
- `measureLineColor: [1, 0, 0, 1]` (the color of the line drawn by the tool)
- `measureTextHeight: 0.04` (fractional height, separate from main textHeight property for orientation labels)
@jennydaman , I have added you as a co-author to this commit since the implementation uses your code referenced in issue #1090. Feel free to edit as needed. 
You can run `npm run dev` on this branch to see a demonstration (use right click + drag on the canvas). 
- #1090

add options for measure tool display behaviour

---

packages/niivue/src/index.html
packages/niivue/src/niivue/index.ts
packages/niivue/src/nvdocument.ts

This PR introduces new functionality that allows users to set the "drag mode" of the primary mouse button (the left button) and for single finger touch drags. 
we have a new `DRAG_MODE_PRIMARY` enum with the options:
- `DRAG_MODE_PRIMARY.windowing`
- `DRAG_MODE_PRIMARY.crosshair` (this is the default to preserve existing functionality)
What does the new windowing click and drag movement do?
- click and drag up in the canvas to make things brighter (moves the display range uniformly lower)
- click and drag down to make things darker (moves the display range uniformly higher)
- click and drag left to increase the contrast (makes the display range more narrow)
- click and drag right to decrease the contrast (makes the display range wider)
- These movements also work in volume rendering (3D) …

implement new drag mode for adjusting window and level

---

packages/niivue/src/niivue/index.ts
packages/niivue/src/nvdocument.ts

- Use the loadingText values specificed with opts
- Keep this.opts.loadingText as the state to use
- If loadingText is empty, do not execute the draw

Use opts.loadingText

---

packages/niivue/src/niivue/index.ts
packages/niivue/src/niivue/utils.ts
packages/niivue/types.d.ts

This PR allows the niivue file drop handler to load images that require custom loaders. Note that the custom loaders must first be added to the list of known file loaders (usually right after initialising a new niivue instance). 
I have tested this with the ds-loader and the vox-loader examples. 
This implementation reuses as much existing niivue code as possible. 
To test on your own system:
- clone niivue
- `npm run build:niivue`
- `cp -r ./packages/niivue/build/* /path/to/your/local/repo/node_modules/@niivue/niivue/build/`
- in your local repo with a custom loader and niivue `npm run dev`. For example, this would work in the [ds-loader](https://github.com/rordenlab/ds-loader) repo.

implement loadImages for custom loaders with drag and drop

---

packages/niivue/src/niivue/index.ts

- Two click for undo of filled drawing

Avoid double unclick to undo filled drawing.

---

packages/niivue/src/niivue/index.ts

This will remove the window 'resize' event observer and disconnect the
resizeObserver.
A MutationObserver is also added for the attached canvas's parent so
this method is called whenever the canvas associated with a Niivue
instance is removed.
This cleans up references / addresses memory leaks, and e.g. prevents invalid
calls to this.resizeListener with a window resize after the associated
canvas has been removed from the DOM.

Start cleanup method

---

packages/niivue/src/nvimage/index.ts

copy Uint8Array before assigning from url - this fixes a problem when the Uint8Array is a view with a different size to the ArrayBuffer
I created this as a PR instead of an issue, since I can point to the code.
The issue came up for me, when I used a Julia package for sending objects to javascript (Bonito.jl). The data sent from julia is a Uint8Array, but the size of the underlying ArrayBuffer is different. This is the error I received:
index.ts:591 Uncaught (in promise) Error: Failed to parse NIfTI file image.nii.
at _NVImage.new (index.ts:591:17)
at async _NVImage.loadFromUrl (index.ts:3289:15)
at async index.ts:2304:22
at async Promise.all (index 0)
at async Niivue.addVolumesFromUrl (index.ts:2314:21)
at async Niivue.loadVolumes (index.ts:4692:5)
The size of my Uint8Array was 282928, …

Fix problem, when url is a Uint8Array that is a view of a larger ArrayBuffer

---

packages/niivue/bundle.js
packages/niivue/bundleForDemos.js

This is Anthony Androulakis' [Update bundle scripts for saving as HTML](https://github.com/niivue/niivue/pull/1312) rebased on niivue/main.
Fixes issue:
- https://github.com/niivue/niivue/issues/1309
This also essentially fixes this issue on ipyniivue:
- https://github.com/niivue/ipyniivue/issues/117
Mangle is set to false to preserve export names. 
Additionally, I added the noExternal setting to bundle.js so that the index.min.js for non-demo purposes is standalone (this is useful for applications in ipyniivue).

Update bundle scripts for saving as HTML

---

packages/niivue/src/nvdocument.ts

This PR attempts to introduce quality-of-life improvements to `NVDocument.json()`
- Introduces a new parameter, `embedDrawing` to control the population of `encodedDrawingBlob`
- If imageOptions does not exist for a particular volume, tries to set reasonable defaults from the volume itself
- None

[ENH] Quality-of-life enhancements to NVDocument.json()
