.prettierignore
package-lock.json
package.json
src/niivue.js
src/shader-srcs.js
src/shader.js

now when building the `prettier` code formatter is used. This ensures all future builds result in consistently formatted source code. You can write source code any way you like, but keep in mind it will be reformatted when you build, demo, or test `niivue`
https://github.com/prettier/prettier

enforce prettier code style

---

package-lock.json
package.json
src/index.html
src/niivue.js
src/nvimage.js

list of changes:
- each `NVImage` now has an `id` property with an assigned uuid (this enables some image finding/sorting routines)
- implemented `moveVolumeToBottom` to move a selected volume to the bottom of the stack (makes it the background)
- implemented `moveVolumeToTop` to move a selected volume to the top of the stack
- implemented `moveVolumeUp` to move a volume up one index in the stack
- implemented `moveVolumeDown` to move a volume down one index in the stack
- implemented `getVolumeIndexByID` to query a given volume's index by its `id` property
- implemented `getOverlayIndexByID` (similar to above) maybe not used much though. 
- updated the implantation of `setVolume`

implement image reordering routines; closes #179; closes #180

---

README.md

update readme with link to dev docs; closes #181

---

demos/features/basic.multiplanar.html
src/index.html
src/niivue.js

As discussed in https://github.com/niivue/niivue/issues/201

Adding getter/setter for isRadiologicalConvention to allow correct viewing of chest CT scans 

---

README.md

fixes the warning and bug noted in https://github.com/niivue/niivue/issues/252

updated vue and react examples

---

src/niivue.js
src/shader-srcs.js

Experimental clip plane interaction (drag to set azimuth/elevation; pinch/scroll wheel for depth). List of fixed issues:
- [issue 70](https://github.com/niivue/niivue/issues/70)
- [issue 71](https://github.com/niivue/niivue/issues/71)

Clip planes

---

src/niivue.js
src/nvimage.js

fix paired hdr and img drag and drop

---

package-lock.json
package.json
src/niivue.js

added hjkl ctrl+u ctrl+d shortcuts for moving crosshairs or rotating 3d scene. 
@jbteves may find them interesting ;) (or other vim users)

add vim style hjkl ctrl-u and ctrl-d shortcuts

---

src/index.html
src/nvimage.js

add save to disk feature; if name ends with .gz then uses fflate compression

---

src/nvimage.js
src/nvmesh.js

Ensure NIfTI writing preserves endian of SForm
```
view.setFloat32(280 + FLOAT32_SIZE * i, flattened[i], hdr.littleEndian);
```

Fix NIfTI-Reader-JS NIfTI to Buffer bug

---

README.md
src/shader-srcs.js

mesa kludge1 from MRIcroGL

---

demos/features/draw2.html
src/niivue.js
src/shader-srcs.js

- [Issue 339](https://github.com/niivue/niivue/issues/339)

Rendering shows drawing (https://github.com/niivue/niivue/issues/339)

---

src/niivue.js
src/nvimage.js

add support for dicom folder drag and drop

---

README.md
demos/features/basic.multiplanar.html
package-lock.json
package.json
src/niivue.js
src/nvimage.js
vite.config.js

- #354 
needed to update the vite config to include the commonjs plugin so that daikon is bundled correctly

Dicom support

---

src/niivue.js
tests/test.defaultOptions.js

update JSDoc properties

---

demos/features/mosaics2.html
demos/features/ui.html
demos/features/worldspace2.html
demos/index.html
src/index.html
src/niivue.js

List of fixed issues:
- multiplanarForceRender option [404](https://github.com/niivue/niivue/issues/410)
- Do not open drawing as overlay [410](https://github.com/niivue/niivue/issues/410)
- Show cross-lines on axial mosaics correctly [411](https://github.com/niivue/niivue/issues/411)

Minor fixes

---

src/meshes.html
src/nvmesh.js

allow loading meshes with query strings

---

src/index.html
src/logger.js
src/niivue.js
vite.config.js

add package version as __NIIVUE_VERSION__ in vite config; remove console.log statements

---

README.md
demos/features/tracts.html

- [Update suggested minimal code, clean up html for tracts demo](https://github.com/niivue/niivue/issues/498)

Thresholding

---

src/nvdocument.js
src/nvimage.js
src/nvmesh.js

add isAntiAlias default; base64 updates

---

src/nvmesh.js

Linked to https://github.com/nilearn/nilearn/issues/3451#issuecomment-1416174323.
Partially addresses #507.

Allow float64 arrays in NVMesh.readGII

---

src/niivue.js

document properties for loadVolumes method

---

package.json

update JSDoc theme to remove deplicate entries

---

demos/features/atlas.html
demos/features/pointset.html
demos/features/shiny.volumes.html
src/niivue.js
src/nvimage.js
src/nvmesh.js
src/shader-srcs.js

FreeSurfer footer (https://github.com/niivue/niivue/issues/675)

---

.github/workflows/test-linux-node20.yml
.github/workflows/test-macOS-node20.yml
.github/workflows/test-windows-node20.yml

build and test on non-EOL node versions

---

package-lock.json
package.json

Mnt bump ver 0.37.1

---

demos/features/pointset.html
demos/features/shiny.volumes.html
package-lock.json
package.json
src/niivue.js
src/nvmesh.js

- #695 this makes sense for all gestures, with the possible exception of the panning gesture.

Constrain drags to initial tile 

---

demos/features/layout.html
demos/index.html
src/niivue.js
src/nvdocument.js

Specify multi planar layout 

---

src/niivue.js

- avoid syncing with itself, #709

avoid syncing with itself

---

src/niivue.js

removed commented line

---

package-lock.json
package.json
src/index.html
src/niivue.js

Fix rescale thumbnail

---

.eslintrc.js
src/colortables.js
src/niivue-object3D.js
src/niivue/index.js
src/niivue/utils.js
src/nvconnectome.js
src/nvimage/index.js
src/nvimage/utils.js
src/nvmesh-loaders.js
src/nvmesh-utilities.js
src/nvmesh.js

- #755 
added new curly config to eslint and run `npx eslint --fix .` to update all block statements with curly brackets.

added curly config

---

package-lock.json
package.json
src/niivue/index.js
src/nvmesh.js

- fixes the broken outline setting for mesh atlases (closes #754) 
- closes #759 too

Bug atlas outline

---

src/nvmesh-loaders.ts
src/nvmesh-types.ts
src/nvmesh.ts
src/types.ts

This is a follow-up to #775.
Migrates `nvmesh.js` to TypeScript. This was already a bit more messy than the files in #775 😅 
This and the following PRs can either be reviewed and then merged into #775, or #775 first and then merge this and the following PRs into main directly.

TypeScript Migration - NVMesh

---

package.json
src/nvconnectome.ts
src/nvlabel.ts
src/nvmesh.ts
src/types.ts

TypeScript Migration - NVConnectome

---

src/nvcontroller.ts
src/nvimage/utils.ts
src/nvmesh.ts
src/nvmessage.ts
src/session-bus.ts
src/types.ts

TypeScript Migration - NVController

---

src/niivue/index.js
src/nvdocument.ts
src/nvimage/index.ts
src/nvimage/utils.ts
src/nvmesh.ts

requests
- add experimental support for headers in fetch requests #776

Fix import statements and add headers to fetch

---

demos/features/afni.html
demos/features/layout.html
demos/features/test_images.html
demos/features/timeseries.html
demos/features/timeseries2.html
src/nvmesh-loaders.ts
src/nvmesh.ts

@jens-ox please consider accepting this PR to your repository. It includes fixes several of the live demos and other issues: 
- #797 
- #796
- #795
- #793 
- #792

Typescript fix

---

src/niivue/index.ts
src/nvimage/index.ts
src/shader-srcs.ts

@jens-ox can you merge this into your PR. I can do more work to clean up the shaders, but this should restore functionality.
- #799

Drawing render kludge (https://github.com/niivue/niivue/issues/799)

---

demos/features/test_images.html
src/nvimage/index.ts
src/nvmesh.ts

- It does not solve #793, but at least fails gracefully (fixed the try catch, and formatted the string better).

Allow graceful failure of fetchPartial range

---

src/niivue/index.ts

fix loadVolumes types

---

.eslintrc.cjs
playwright/e2e/helpers.js
playwright/e2e/test.niivue.attachTo.spec.js
playwright/e2e/test.niivue.calMinMax.do_not_trust_header.spec.js
playwright/e2e/test.niivue.colormap.spec.js
playwright/e2e/test.niivue.draw.2D.cullFrontFace.spec.js
playwright/e2e/test.niivue.draw.3D.clipPlane.spec.js
playwright/e2e/test.niivue.draw.3D.crosshairs.spec.js
playwright/e2e/test.niivue.draw.3D.noCrosshairs.spec.js
playwright/e2e/test.niivue.event.onLocationChange.4D.spec.js
playwright/e2e/test.niivue.load.connectome.tabular.spec.js
playwright/e2e/test.niivue.load.fileFormats.spec.js
playwright/e2e/test.niivue.load.nifti.compressed.spec.js
playwright/e2e/test.nvmeshloaders.readLayer.spec.js

#List of fixed issues (if they exist):
- [turn off multisampling in niivue tests](https://github.com/niivue/niivue/issues/809)
-
-

Feature add test option for NiiVue constructor to turn off isAntiAlias and isHighResolutionCapable in tests with screen shots

---

src/niivue/index.ts
src/nvdocument.ts
src/nvimage/index.ts
tests/noci.test.wasmProcessImageAsOverlay.js
tests/unit/nvdocument.colormap.test.ts

- Fixed [colorMap name is case sensitive](https://github.com/niivue/niivue/issues/813)
- Added unit test
- Changed colorMap and colorMapNegative to colormap and colormapNegative respectively in .nvd files

Fix demo document colormap

---

package-lock.json
package.json
src/niivue/index.ts

- should fix #819 and some angular build errors show when investigating #831

fix bug related to font types variable initialisation in index.d.ts

---

src/nvmesh-loaders.ts

- TRK voxel shift (https://github.com/niivue/niivue/issues/850)

TRK voxel shift (https://github.com/niivue/niivue/issues/850)

---

demos/features/basic.multiplanar.html

add missing await in  basic.multiplanar example demo

---

playwright/e2e/test.niivue.load.connectome.tabular.spec.js
playwright/e2e/test.niivue.loadConnectome-with-labels.spec.js
src/index.html
src/niivue/index.ts
src/nvimage/index.ts

- allow colorbarVisible property when using loadVolumes; closes #848

allow setting colorbarVisible in loadVolumes

---

demos/features/tracts.atlas.html

- new [atlas live demo](https://niivue.github.io/niivue/features/tracts.atlas.html) does not work when run on case-sensitive file system (`yeh2022` vs `Yeh2022`).

Case sensitive filenames

---

demos/features/modulate.html
demos/features/tracts.group.html
demos/features/tracts.html
src/niivue/index.ts
src/nvdocument.ts
src/nvimage/index.ts
src/nvmesh-loaders.ts
src/shader-srcs.ts

Per voxel V1 lines

---

src/concat_json2trx.mjs

- Fix eslint issues and minor bug in `concat_json2trx.mjs`

[FIX] eslint and minor bug

---

README.md
demos/features/clipplanes.html
demos/features/mesh.atlas.gii.html
demos/features/sync.mesh.html
demos/features/tracts2.html
src/colortables.ts
src/nvimage/index.ts
src/nvmesh-loaders.ts
src/nvmesh.ts

- closes #896 
- closes #895
- closes #893

Closing recent issues and suggestions

---

docs/development-notes/webgl.md
src/niivue/index.ts
src/shader-srcs.ts

WebGL Texture refactor (https://github.com/niivue/niivue/issues/920)

---

bundleForDemos.js
src/niivue/index.ts

remove rxjs loading subject and allow external modules in demo bundle

---

demos/features/conform.html
demos/features/label_clusters.html
demos/features/slab_selection.html
demos/index.html
src/niivue/index.ts
src/nvimage/index.ts

- Experimental solution for #663
- Allows conform to align to LIA (FastSurfer/FreeSurfer) or RAS (somewhat similar to nibabel)
- AI live demos improved

Read and write voxel slabs

---

src/niivue/index.ts
src/nvdocument.ts

- #966 partial fix (catches undefined values in scene data, we should make sure saved scenes do define azimuth and elevation)

Undefined scene error (https://github.com/niivue/niivue/issues/966)

---

demos/features/draganddrop.html

- fix `loadFromFile` in drag and drop demo

Fix file open dialog bug in demo

---

src/niivue/index.ts
src/nvdocument.ts

- Extend NVDocument to store new streamline properties.

Doc fiber fix

---

src/nvimage/index.ts

NRRD (https://github.com/niivue/niivue/issues/974)

---

demos/features/denoise.html

- Removes blue fringe from buttons in denoise live demo.

DIV has its own color

---

demos/features/clipplanes.html
demos/features/clipplanes2.html
demos/index.html
playwright/e2e/test.niivue.saveDocument.spec.ts
src/niivue/index.ts
src/nvdocument.ts
src/shader-srcs.ts

- #999 
@cdrake this adds three new properties to the scene data: clipThick, clipVolumeLow, clipVolumeHigh. For backward compatibility it is important that these are set to the default values if not present in a NVD document. Likewise, we should make sure to retain this data when we save scenes as NVD documents.

Volume clipping

---

demos/features/modulateDSI.html
demos/index.html

Improve DSI-Studio FIB file support

---

src/nvimage/index.ts

Support V1 in DSI-Studio FIB

---

playwright/e2e/test.niivue.broadcastTo.spec.ts
src/nvdocument.ts

Fix unwanted syncing

---

demos/features/mosaics.html
src/niivue/index.ts
src/nvmesh.ts
src/shader.ts

- closes #1011
- closes #877
- closes #1017

Optimize GPU usage

---

demos/features/sync.bidirectional.html
playwright/e2e/test.niivue.broadcastTo.spec.ts
playwright/e2e/test.niivue.loadDocumentFromUrl.spec.ts
src/niivue/index.ts
src/nvdocument.ts

- fixes [zoom sync with other nv instances](https://github.com/niivue/niivue/issues/992#top)
- adds test to verify 2d pan/zoom is not syncing after syncing is turned of
- adds more functionality to bidirectional sync demo
- adds zoom to 3d syncing

Fixes unwanted 2d pan/zoom syncing between NiiVue instances and adds 3d zoom for 3d syncing

---

demos/features/draw.ui.html
demos/features/mosaics.html
src/index.html
src/niivue/index.ts
src/nvdocument.ts

This PR adds a new feature: click-to-segment.
Clinical medical images often have lesions that users need to segment in order to use these lesion masks in their analyses. These lesions can be bright or dark depending on the pathology and the image modality. 
Lesion masks can be time consuming to draw manually, even though NiiVue provides great drawing tools already.
The `clickToSegment` feature builds on the existing NiiVue drawing tools. It first creates an 2D circular ROI at the clicked location, and then uses that ROI as the cluster input for the `drawFloodFill` method that can grow ROIs (a.k.a clusters) based on the intensity range within the ROI. The `clickToSegment` feature provides a streamlined workflow for creating masks when the lesion is relatively homogenous in its intensity …

New Feature: click to segment

---

demos/features/mesh.atlas.html
demos/features/mesh.create.html
demos/features/mesh.loader.html
demos/index.html
src/niivue/index.ts
src/nvimage/index.ts
src/nvmesh-loaders.ts
src/nvmesh-utilities.ts
src/nvmesh.ts

Mesh utilities and fixing the depth picker

---

.github/workflows/testing_and_linting.yml
package-lock.json
package.json

This PR updates some of the dev dependencies

chore: package maintenance

---

.github/workflows/testing_and_linting.yml
package-lock.json
package.json
src/niivue/index.ts
src/nvimage/utils.ts
src/shader-srcs.ts

Small fixes

---

playwright.config.js
src/nvimage/index.ts
src/nvmesh-loaders.ts

MHD support (https://github.com/niivue/niivue/issues/1042)

---

demos/features/timeseries.html
demos/features/timeseries2.html

List of fixed issues:
timeseries.html:
- forward button does not move forward  
timeseries2.html:
- forward button jumps to wrong volume if volume was previously changed by clicking on graph
both:
- back button jumps to frame 0 if volume was changed by clicking on graph
- animate starts from incorrect frame if volume was changed by clicking on graph

fixed button behavior for time series demos

---

src/index.html
src/niivue/index.ts

Orientation Label Regression

---

src/nvdocument.ts

Sets initial values for crosshairPos and pan2Dxyzmm

Set initial vec3 and vec4 data for document

---

src/index.html
src/niivue/index.ts
src/nvdocument.ts

Tile Margin (https://github.com/niivue/niivue/issues/1062)

---

demos/features/layout.html
src/index.html
src/niivue/index.ts
src/nvconnectome.ts
src/nvdocument.ts

nodes simplification (https://github.com/niivue/niivue/issues/1080)

---

tests/unit/nvdocument.test.ts

enhancement: unit tests for loadFromFile method in NVDocument class.

enhance unit tests

---

src/niivue/index.ts

- [Fixed missing legend text](https://github.com/niivue/niivue/issues/1099)

Fixed missing legend text

---

packages/niivue/package.json

bump version for release

---

package-lock.json
packages/niivue-desktop/package.json
packages/niivue-desktop/src/renderer/src/components/OptionsTab.tsx
packages/niivue-desktop/src/renderer/src/components/SceneTabs.tsx

#1134 add color picker for color options

Options tab

---

packages/niivue/demos/features/save.custom.html.html
packages/niivue/src/niivue/index.ts
packages/niivue/src/nvdocument.ts
packages/niivue/src/nvutilities.ts

- Fixes the Save a Scene as HTML demo
- Fixes the Save a Scene with Custom HTML demo

Fix save html

---

packages/niivue-desktop/src/renderer/src/components/ColorPickerControl.tsx
packages/niivue-desktop/src/renderer/src/components/GeneralTab.tsx
packages/niivue-desktop/src/renderer/src/components/OptionsTab.tsx
packages/niivue-desktop/src/renderer/src/components/SceneTabs.tsx

- Extracts out color picking into a separate control
- Consolidate General and Options tabs

Create color picker control. Consolidate general and options tabs

---

package-lock.json
packages/niivue-desktop/package.json
packages/niivue-desktop/src/renderer/src/components/MeshImageCard.tsx
packages/niivue-desktop/src/renderer/src/components/VolumeImageCard.tsx

- Replaces check boxes for visibility with icons

Visibilty-icon

---

.gitignore
package-lock.json
packages/niivue-desktop/package.json
packages/niivue-desktop/src/renderer/src/components/MeshImageCard.tsx
packages/niivue-desktop/src/renderer/src/components/MeshLayerCard.tsx
packages/niivue-desktop/src/renderer/src/components/VolumeImageCard.tsx

- Changed visibility icons to radix-ui react icons, removed @mui dependencies

Changed visibility icons to radix-ui react icons added visibility icons to mesh layer card.

---

packages/niivue/src/nvimage/index.ts
packages/niivue/src/nvimage/utils.ts

Work in progress experiment trying out compression streams API instead of fflate to speed up image loading.
Right now this only implements NIfTI URL loading.
I have been using this larger 4d image for testing:
```javascript
var volumeList1 = [
{
url: "https://fcp-indi.s3.amazonaws.com/data/Projects/HBN/MRI/Site-CBIC/sub-NDARAA396TWZ/func/sub-NDARAA396TWZ_task-movieTP_bold.nii.gz",
limitFrames4D: 5
},
]
```
<details>
<summary>Full example code</summary>
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width,initial-scale=1.0" />
<title>time series demo</title>
<link rel="stylesheet" href="niivue.css" />
<style>
.unstyled-button {
border: none;
padding: 0;
background: …
```

[WIP] Compression Streams API

---

packages/niivue-desktop/postcss.config.js
packages/niivue-desktop/src/common/sliceTypes.ts
packages/niivue-desktop/src/main/index.ts
packages/niivue-desktop/src/main/utils/menu.ts
packages/niivue-desktop/src/renderer/src/components/SceneTabs.tsx
packages/niivue-desktop/src/renderer/src/ipcHandlers/menuHandlers.ts

This PR ensures that the application menu bar appears on all platforms. I have also fixed code formatting in the desktop package by running `npm run lint`. 
@cdrake , this should fix the menu bar issue you were having. I would recommend that we merge this into main, and then you rebase your branch on main.

enable menubar on all platforms; lint

---

packages/niivue/src/index.html

This PR fixes the bug in index.html (niivue/src/index.html) where an old dicom-loader import was present.

remove dicom loader import

---

packages/niivue-desktop/src/renderer/src/App.tsx
packages/niivue-desktop/src/renderer/src/components/EnumSelect.tsx
packages/niivue-desktop/src/renderer/src/components/GeneralTab.tsx
packages/niivue-desktop/src/renderer/src/components/MeshImageCard.tsx
packages/niivue-desktop/src/renderer/src/components/Sidebar.tsx
packages/niivue-desktop/src/renderer/src/components/VolumeImageCard.tsx
packages/niivue-desktop/src/renderer/src/utils/config.ts
packages/niivue/src/nvdocument.ts

- Allow users to reorder volumes
- Add EnumSelect to update enums in NVConfigOptions

Order volumes

---

packages/niivue-desktop/src/renderer/src/components/Viewer.tsx

- Fixes duplicate volumes and meshes being added on state updates

Fixes duplicate volumes or meshes being added

---

packages/niivue/package.json
packages/niivue/src/nvimage/index.ts
packages/niivue/tests/unit/nvimage.test.ts

update to async readHeader and work on tests

---

packages/niivue/demos/index.html
packages/niivue/src/niivue/index.ts

- Removed links in index.html
- Removed links from doc comments

Remove multiuser demo links

---

packages/niivue/demos/features/test_images.html
packages/niivue/demos/features/timeseries2.html
packages/niivue/src/nvimage/index.ts
packages/niivue/src/nvimage/utils.ts
packages/niivue/src/nvutilities.ts

Voxel format support

---

packages/niivue/src/index.html
packages/niivue/src/niivue/index.ts
packages/niivue/src/nvimage/index.ts

ZARR 3D and 2D (RGB and scalar)

---

packages/niivue/src/index.html
packages/niivue/src/niivue/index.ts

- #1233 
- Draw on 2D slices of huge 3D images

Draw on 2D slices of huge 3D images

---

.gitignore
packages/niivue/demos/features/draw.ui.html
packages/niivue/demos/features/magic_wand.html
packages/niivue/demos/index.html
packages/niivue/src/index_magic.html
packages/niivue/src/niivue/index.ts

This PR implements the live preview mode of the magic wand masking tool (clickToSegment). This works best in 2D with the relevant clickToSegment flags.

magic wand improvements (clickToSegment)

---

packages/niivue/src/niivue/index.ts
packages/niivue/src/nvmesh.ts

fix issue 1256 - setting mesh properties

---

packages/niivue/src/niivue/index.ts
packages/niivue/src/nvdocument.ts

In this PR, I have added the option to show/hide the border of the colorbar, and also change the width of the colorbar (0 to 1, proportional to the canvas width).

Add colorbar width and border options to NVConfigOptions

---

packages/niivue/src/index.html
packages/niivue/src/niivue/index.ts

- Introduced `setCustomLayout`, `clearCustomLayout`, and `getCustomLayout` methods.
- Implemented custom layout handling in `drawSceneCore`. Custom layouts have higher priority than built-in layouts.
- Updated hot-reloadable index.html to include a toggle button for custom layouts during development.
```javascript
// Layout format: {sliceType: SLICE_TYPE, position: [left, top, width, height]}
// Units are relative (0-1) to canvas size
const customLayout = [
// Left 50% - Sag
{sliceType: SLICE_TYPE.SAGITTAL, position: [0, 0, 0.5, 1.0]},
// Top right - Cor
{sliceType: SLICE_TYPE.CORONAL, position: [0.5, 0, 0.5, 0.5]},
// Bottom right - Ax
{sliceType: SLICE_TYPE.AXIAL, position: [0.5, 0.5, 0.5, 0.5]}
];
// Apply the custom layout
nv1.setCustomLayout(customLayout);
// clear the custom layout …
```

Add custom layout functionality and related methods to Niivue

---

packages/niivue/README.md
packages/niivue/demos/features/labels.connectomes.html
packages/niivue/demos/features/mesh.freesurfer.aaOFF.html
packages/niivue/demos/features/mesh.freesurfer.aaON.html
packages/niivue/demos/features/mesh.freesurfer.html
packages/niivue/demos/features/meshes.html
packages/niivue/demos/features/mosaics.html
packages/niivue/demos/features/mosaics2.mesh.html
packages/niivue/demos/index.html
packages/niivue/src/niivue/index.ts
packages/niivue/src/nvmesh-loaders.ts

Horizontal overlap for mosaics

---

packages/docs/docs/Loading images.mdx
packages/docs/docs/colormaps.mdx
packages/docs/docs/examples/colormaps.mdx
packages/docs/docs/index.mdx
packages/docs/docs/meshes.mdx
packages/docs/docs/volumes.mdx
packages/docs/src/components/ColormapDemo.jsx

This PR updates some of the docusaurus docs.

Add more docs

---

packages/docs/src/pages/gallery.js
packages/docs/src/pages/gallery.module.css

This PR updates the gallery page and the cards to have a defined header with title and buttons, and the thumbnail image is displayed below the header rather than as the background of the card.

Refactor gallery and card appearance

---

packages/niivue/playwright.config.js

- Allows playwright tests to run locally on Linux

fix playwright config for e2e test on Linux

---

package-lock.json
package.json
packages/niivue-uikit/index.html
packages/niivue-uikit/package.json
packages/niivue-uikit/src/index.ts
packages/niivue-uikit/tsconfig.json
packages/niivue-uikit/vite.config.ts
packages/niivue/src/test-uikit-components.html
packages/uikit/index.html
packages/uikit/package.json
packages/uikit/src/assets/uikfont.ts
packages/uikit/src/components/UIKButton.ts
packages/uikit/src/components/UIKColormapSelector.ts
packages/uikit/src/components/UIKPanel.ts
packages/uikit/src/components/UIKSlider.ts
packages/uikit/src/components/UIKToggle.ts
packages/uikit/src/components/UIKViewModeSelector.ts
packages/uikit/src/components/index.ts
packages/uikit/src/index.ts
packages/uikit/src/shaders/frag/circle.frag.glsl
packages/uikit/src/shaders/frag/rotated-font.frag.glsl
packages/uikit/src/shaders/frag/rounded-rect.frag.glsl
packages/uikit/src/shaders/vert/rect.vert.glsl
packages/uikit/src/types.ts
packages/uikit/src/uikrenderer.ts
packages/uikit/tests/index.test.ts
packages/uikit/types/niivue-ui.d.ts

- This PR introduces a new @niivue/niivue-uikit package that demonstrates the integration of UIKit components with Niivue for medical imaging applications. The package serves as a comprehensive example to implement WebGL-based UI controls in the medical imaging workflows.
- **New Package:** packages/niivue-uikit/ with complete medical imaging demo.
- **Interactive Components:** Sliders, toggles, buttons, and selectors for medical parameter control
- **Dev Workflow:** Added npm run dev:uikit script for easy demo access
- **TypeScript Integration:** Proper type definitions and build configuration
- **Medical Controls:** Brightness, contrast, zoom, opacity, and slice navigation sliders
- **View Controls:** Crosshair, colorbar, radiological convention toggles
- **Action Buttons:** Screenshot, …

feat: Add niivue-uikit demo package showcasing WebGL UIKit medical imaging integration

---

package-lock.json
package.json
packages/niivue-uikit/index.html
packages/niivue-uikit/package.json
packages/niivue-uikit/src/index.ts
packages/niivue-uikit/tsconfig.json
packages/niivue-uikit/vite.config.ts
packages/uikit/index.html
packages/uikit/package.json
packages/uikit/src/assets/uikfont.ts
packages/uikit/src/components/UIKButton.ts
packages/uikit/src/components/UIKColormapSelector.ts
packages/uikit/src/components/UIKPanel.ts
packages/uikit/src/components/UIKSlider.ts
packages/uikit/src/components/UIKToggle.ts
packages/uikit/src/components/UIKViewModeSelector.ts
packages/uikit/src/components/index.ts
packages/uikit/src/index.ts
packages/uikit/src/shaders/frag/circle.frag.glsl
packages/uikit/src/shaders/frag/rotated-font.frag.glsl
packages/uikit/src/shaders/frag/rounded-rect.frag.glsl
packages/uikit/src/shaders/vert/rect.vert.glsl
packages/uikit/src/types.ts
packages/uikit/src/uikrenderer.ts
packages/uikit/tests/index.test.ts
packages/uikit/types/niivue-ui.d.ts

Pull to main

---

packages/niivue/package.json

chore: update version to 0.60.0 in package.json

---

package-lock.json
packages/niivue-desktop/electron-builder.yml
packages/niivue-desktop/electron.vite.config.ts
packages/niivue-desktop/package.json
packages/niivue-desktop/scripts/afterSign-clean.cjs
packages/niivue-desktop/scripts/clean-xattrs-afterpack.js
packages/niivue-desktop/scripts/custom-sign.cjs
packages/niivue-desktop/scripts/prebuild-clean-helpers.cjs
packages/niivue-desktop/src/main/utils/ipcHandlers.ts
packages/niivue-desktop/src/main/utils/menu.ts
packages/niivue-desktop/src/preload/index.ts
packages/niivue-desktop/src/renderer/src/MainApp.tsx
packages/niivue-desktop/src/renderer/src/types/electron-api.d.ts

- Establishes notarization workflow for desktop app

Initial commit for publishing workflow of desktop app

---

README.md
packages/docs/docusaurus.config.js
packages/niivue/demos/features/draw.ui.html
packages/niivue/demos/index.html

- Illustrate penSize #1364 
- Consistent case for recipes
- Fix broken URL

Fix links and add recipe with penSize()

---

packages/niivue/demos/features/atlas.allen.html
packages/niivue/demos/features/atlas.bigbrain.html
packages/niivue/demos/features/atlas.julich.html
packages/niivue/demos/features/atlas.mgz.html
packages/niivue/demos/features/atlas.thalamus.html
packages/niivue/demos/features/sync.mesh.html
packages/niivue/demos/index.html
packages/niivue/src/niivue/index.ts
packages/niivue/src/nvimage/VolumeUtils.ts
packages/niivue/src/shader-srcs.ts

- Fixes #1369 
- This also [fixes an issue with the conform function](https://github.com/niivue/brain2print/issues/12) for images with [data scaling](https://brainder.org/2012/09/23/the-nifti-file-format/). The array `img` is redeclared in a conditional, which is subsequently out of scope.

Atlas demos and improved atlas shader

---

packages/niivue/src/niivue/index.ts

avoid getter

---

packages/niivue/src/niivue/index.ts
packages/niivue/src/nvimage/index.ts

Fix floodfill

---

packages/niivue/src/niivue/index.ts

The `mouseLeaveListener` was not removed in the `cleanup` method. This PR uses AbortController to prevent forgetting to call `removeEventListener`.

Use AbortController to clean up event listeners
